# Generated by Django 4.0.2 on 2022-08-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='doctor/profile_pic'),
            preserve_default=False,
        ),
    ]
