# Generated by Django 4.0.2 on 2022-08-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='Image_Url',
            field=models.ImageField(upload_to='media/profile_course_pic'),
        ),
    ]
