# Generated by Django 4.0.2 on 2022-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_packing_cost_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
