# Generated by Django 4.0.2 on 2022-08-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_packing_cost_alter_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
