# Generated by Django 4.0.2 on 2022-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_doctor_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('select_date', models.CharField(max_length=100)),
                ('contact_type', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
            ],
        ),
    ]
