# Generated by Django 4.0.2 on 2022-08-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='doctor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
            preserve_default=False,
        ),
    ]
