# Generated by Django 4.0.2 on 2022-08-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_booking_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doctor_id',
            new_name='doctor_name',
        ),
    ]
