# Generated by Django 4.0.2 on 2022-08-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_doctor_id_booking_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='select_date',
            new_name='date',
        ),
    ]
